/*
 * Unity Catalog API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.unitycatalog.server.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * All possible model version statuses (UNKNOWN, PENDING, FAILED, READY). PENDING status indicates that the client has not completely written all model artifacts to external storage. FAILED status indicates that the client has failed to write all model artifacts to external storage. READY status indicates that the client has successfully written all model artifacts to external storage. 
 */
public enum ModelVersionStatus {
  
  UNKNOWN("UNKNOWN"),
  
  PENDING("PENDING"),
  
  FAILED("FAILED"),
  
  READY("READY");

  private String value;

  ModelVersionStatus(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ModelVersionStatus fromValue(String value) {
    for (ModelVersionStatus b : ModelVersionStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

