
services:
  mysql-db:
    image: mysql:8.4.1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ucdb
      MYSQL_USER: uc_default_user
      MYSQL_PASSWORD: uc_default_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  mysql_data: