/*
 * Unity Catalog API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.unitycatalog.server.persist.model;

import io.unitycatalog.server.model.Privilege;

/** The privilege to grant. */
public enum Privileges {
  METASTORE_ADMIN("METASTORE ADMIN"),

  OWNER("OWNER"),

  CREATE_CATALOG("CREATE CATALOG"),

  USE_CATALOG("USE CATALOG"),

  CREATE_SCHEMA("CREATE SCHEMA"),

  USE_SCHEMA("USE SCHEMA"),

  READ_VOLUME("READ VOLUME"),

  SELECT("SELECT"),

  EXECUTE("EXECUTE");

  private String value;

  Privileges(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Privileges fromValue(String value) {
    for (Privileges b : Privileges.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static Privilege toPrivilege(Privileges privilege) {
    try {
      return Privilege.fromValue(privilege.getValue());
    } catch (IllegalArgumentException e) {
      return null;
    }
  }

  public static Privileges fromPrivilege(Privilege privilege) {
    try {
      return Privileges.fromValue(privilege.getValue());
    } catch (IllegalArgumentException e) {
      return null;
    }
  }
}
