# coding: utf-8

"""
    Unity Catalog API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class VolumeOperation(str, Enum):
    """
    VolumeOperation
    """

    """
    allowed enum values
    """
    UNKNOWN_VOLUME_OPERATION = 'UNKNOWN_VOLUME_OPERATION'
    READ_VOLUME = 'READ_VOLUME'
    WRITE_VOLUME = 'WRITE_VOLUME'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of VolumeOperation from a JSON string"""
        return cls(json.loads(json_str))


