# coding: utf-8

"""
    Unity Catalog API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unitycatalog.api.schemas_api import SchemasApi


class TestSchemasApi(unittest.TestCase):
    """SchemasApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SchemasApi()

    def tearDown(self) -> None:
        pass

    def test_create_schema(self) -> None:
        """Test case for create_schema

        Create a schema
        """
        pass

    def test_delete_schema(self) -> None:
        """Test case for delete_schema

        Delete a schema
        """
        pass

    def test_get_schema(self) -> None:
        """Test case for get_schema

        Get a schema
        """
        pass

    def test_list_schemas(self) -> None:
        """Test case for list_schemas

        List schemas
        """
        pass

    def test_update_schema(self) -> None:
        """Test case for update_schema

        Update a schema
        """
        pass


if __name__ == '__main__':
    unittest.main()
