# coding: utf-8

"""
    Unity Catalog API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unitycatalog.api.catalogs_api import CatalogsApi


class TestCatalogsApi(unittest.TestCase):
    """CatalogsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CatalogsApi()

    def tearDown(self) -> None:
        pass

    def test_create_catalog(self) -> None:
        """Test case for create_catalog

        Create a catalog
        """
        pass

    def test_delete_catalog(self) -> None:
        """Test case for delete_catalog

        Delete a catalog
        """
        pass

    def test_get_catalog(self) -> None:
        """Test case for get_catalog

        Get a catalog
        """
        pass

    def test_list_catalogs(self) -> None:
        """Test case for list_catalogs

        List catalogs
        """
        pass

    def test_update_catalog(self) -> None:
        """Test case for update_catalog

        Update a catalog
        """
        pass


if __name__ == '__main__':
    unittest.main()
