# coding: utf-8

"""
    Unity Catalog API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unitycatalog.models.function_parameter_infos import FunctionParameterInfos

class TestFunctionParameterInfos(unittest.TestCase):
    """FunctionParameterInfos unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FunctionParameterInfos:
        """Test FunctionParameterInfos
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FunctionParameterInfos`
        """
        model = FunctionParameterInfos()
        if include_optional:
            return FunctionParameterInfos(
                parameters = [
                    unitycatalog.models.function_parameter_info.FunctionParameterInfo(
                        name = '', 
                        type_text = '', 
                        type_json = '', 
                        type_name = 'BOOLEAN', 
                        type_precision = 56, 
                        type_scale = 56, 
                        type_interval_type = '', 
                        position = 56, 
                        parameter_mode = 'IN', 
                        parameter_type = 'PARAM', 
                        parameter_default = '', 
                        comment = '', )
                    ]
            )
        else:
            return FunctionParameterInfos(
        )
        """

    def testFunctionParameterInfos(self):
        """Test FunctionParameterInfos"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
