# coding: utf-8

"""
    Unity Catalog API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unitycatalog.api.temporary_table_credentials_api import TemporaryTableCredentialsApi


class TestTemporaryTableCredentialsApi(unittest.TestCase):
    """TemporaryTableCredentialsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TemporaryTableCredentialsApi()

    def tearDown(self) -> None:
        pass

    def test_generate_temporary_table_credentials(self) -> None:
        """Test case for generate_temporary_table_credentials

        Generate temporary table credentials.
        """
        pass


if __name__ == '__main__':
    unittest.main()
