# coding: utf-8

"""
    Unity Catalog API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unitycatalog.api.volumes_api import VolumesApi


class TestVolumesApi(unittest.TestCase):
    """VolumesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VolumesApi()

    def tearDown(self) -> None:
        pass

    def test_create_volume(self) -> None:
        """Test case for create_volume

        Create a Volume
        """
        pass

    def test_delete_volume(self) -> None:
        """Test case for delete_volume

        Delete a Volume
        """
        pass

    def test_get_volume(self) -> None:
        """Test case for get_volume

        Get a Volume
        """
        pass

    def test_list_volumes(self) -> None:
        """Test case for list_volumes

        List Volumes
        """
        pass

    def test_update_volume(self) -> None:
        """Test case for update_volume

        Update a Volume
        """
        pass


if __name__ == '__main__':
    unittest.main()
