# coding: utf-8

"""
    Unity Catalog API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unitycatalog.models.catalog_info import CatalogInfo

class TestCatalogInfo(unittest.TestCase):
    """CatalogInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CatalogInfo:
        """Test CatalogInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CatalogInfo`
        """
        model = CatalogInfo()
        if include_optional:
            return CatalogInfo(
                name = '',
                comment = '',
                properties = {
                    'key' : ''
                    },
                created_at = 56,
                updated_at = 56,
                id = ''
            )
        else:
            return CatalogInfo(
        )
        """

    def testCatalogInfo(self):
        """Test CatalogInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
