# coding: utf-8

"""
    Unity Catalog API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unitycatalog.models.create_function import CreateFunction

class TestCreateFunction(unittest.TestCase):
    """CreateFunction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateFunction:
        """Test CreateFunction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateFunction`
        """
        model = CreateFunction()
        if include_optional:
            return CreateFunction(
                name = '',
                catalog_name = '',
                schema_name = '',
                input_params = unitycatalog.models.function_parameter_infos.FunctionParameterInfos(
                    parameters = [
                        unitycatalog.models.function_parameter_info.FunctionParameterInfo(
                            name = '', 
                            type_text = '', 
                            type_json = '', 
                            type_name = 'BOOLEAN', 
                            type_precision = 56, 
                            type_scale = 56, 
                            type_interval_type = '', 
                            position = 56, 
                            parameter_mode = 'IN', 
                            parameter_type = 'PARAM', 
                            parameter_default = '', 
                            comment = '', )
                        ], ),
                data_type = 'BOOLEAN',
                full_data_type = '',
                return_params = unitycatalog.models.function_parameter_infos.FunctionParameterInfos(
                    parameters = [
                        unitycatalog.models.function_parameter_info.FunctionParameterInfo(
                            name = '', 
                            type_text = '', 
                            type_json = '', 
                            type_name = 'BOOLEAN', 
                            type_precision = 56, 
                            type_scale = 56, 
                            type_interval_type = '', 
                            position = 56, 
                            parameter_mode = 'IN', 
                            parameter_type = 'PARAM', 
                            parameter_default = '', 
                            comment = '', )
                        ], ),
                routine_body = 'SQL',
                routine_definition = '',
                routine_dependencies = unitycatalog.models.dependency_list.DependencyList(
                    dependencies = [
                        unitycatalog.models.dependency.Dependency(
                            table = unitycatalog.models.table_dependency.TableDependency(
                                table_full_name = '', ), 
                            function = unitycatalog.models.function_dependency.FunctionDependency(
                                function_full_name = '', ), )
                        ], ),
                parameter_style = 'S',
                is_deterministic = True,
                sql_data_access = 'CONTAINS_SQL',
                is_null_call = True,
                security_type = 'DEFINER',
                specific_name = '',
                comment = '',
                properties = '',
                external_language = ''
            )
        else:
            return CreateFunction(
                name = '',
                catalog_name = '',
                schema_name = '',
                input_params = unitycatalog.models.function_parameter_infos.FunctionParameterInfos(
                    parameters = [
                        unitycatalog.models.function_parameter_info.FunctionParameterInfo(
                            name = '', 
                            type_text = '', 
                            type_json = '', 
                            type_name = 'BOOLEAN', 
                            type_precision = 56, 
                            type_scale = 56, 
                            type_interval_type = '', 
                            position = 56, 
                            parameter_mode = 'IN', 
                            parameter_type = 'PARAM', 
                            parameter_default = '', 
                            comment = '', )
                        ], ),
                data_type = 'BOOLEAN',
                full_data_type = '',
                routine_body = 'SQL',
                routine_definition = '',
                parameter_style = 'S',
                is_deterministic = True,
                sql_data_access = 'CONTAINS_SQL',
                is_null_call = True,
                security_type = 'DEFINER',
                specific_name = '',
                properties = '',
        )
        """

    def testCreateFunction(self):
        """Test CreateFunction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
