# coding: utf-8

"""
    Unity Catalog API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unitycatalog.models.list_volumes_response_content import ListVolumesResponseContent

class TestListVolumesResponseContent(unittest.TestCase):
    """ListVolumesResponseContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListVolumesResponseContent:
        """Test ListVolumesResponseContent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListVolumesResponseContent`
        """
        model = ListVolumesResponseContent()
        if include_optional:
            return ListVolumesResponseContent(
                volumes = [
                    unitycatalog.models.volume_info.VolumeInfo(
                        catalog_name = '', 
                        schema_name = '', 
                        name = '', 
                        comment = '0', 
                        created_at = 56, 
                        updated_at = 56, 
                        volume_id = '', 
                        volume_type = 'MANAGED', 
                        storage_location = '', 
                        full_name = '', )
                    ],
                next_page_token = ''
            )
        else:
            return ListVolumesResponseContent(
        )
        """

    def testListVolumesResponseContent(self):
        """Test ListVolumesResponseContent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
