#!/usr/bin/env bash
# Provisions all AWS resources needed for the credential-vending demo:
#   - S3 bucket for external data
#   - UC Master IAM Role (assumed via IAM Roles Anywhere)
#   - Data Access IAM Role (assumed by UC server via STS)
#   - IAM Roles Anywhere Trust Anchor + Profile
#
# Prerequisites:
#   - AWS CLI v2 configured with sufficient permissions
#   - Certificates generated by generate-certs.sh
#   - jq
#
# All resource identifiers are written to .env so that other scripts
# (configure-uc.sh, demo.sh, teardown-aws.sh) can reference them.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CERT_DIR="${SCRIPT_DIR}/.certs"
ENV_FILE="${SCRIPT_DIR}/.env"

AWS_REGION="${AWS_REGION:-us-east-1}"
PREFIX="${RESOURCE_PREFIX:-uc-demo}"

# ---------------------------------------------------------------------------
# Validate prerequisites
# ---------------------------------------------------------------------------
for cmd in aws jq; do
  if ! command -v "${cmd}" &>/dev/null; then
    echo "ERROR: '${cmd}' is required but not found on PATH." >&2
    exit 1
  fi
done

if [[ ! -f "${CERT_DIR}/ca.crt" ]]; then
  echo "ERROR: CA certificate not found at ${CERT_DIR}/ca.crt" >&2
  echo "       Run generate-certs.sh first." >&2
  exit 1
fi

ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
echo "AWS Account: ${ACCOUNT_ID}  Region: ${AWS_REGION}"

# ---------------------------------------------------------------------------
# S3 Bucket
# ---------------------------------------------------------------------------
BUCKET_NAME="${PREFIX}-data-${ACCOUNT_ID}"
echo ""
echo "==> Creating S3 bucket: ${BUCKET_NAME}"

if aws s3api head-bucket --bucket "${BUCKET_NAME}" 2>/dev/null; then
  echo "    Bucket already exists -- skipping."
else
  if [[ "${AWS_REGION}" == "us-east-1" ]]; then
    aws s3api create-bucket --bucket "${BUCKET_NAME}" --region "${AWS_REGION}"
  else
    aws s3api create-bucket --bucket "${BUCKET_NAME}" --region "${AWS_REGION}" \
      --create-bucket-configuration LocationConstraint="${AWS_REGION}"
  fi
fi

# Upload a small test object so we can verify access later.
echo "hello from unity catalog" | aws s3 cp - "s3://${BUCKET_NAME}/demo/hello.txt"

# ---------------------------------------------------------------------------
# UC Master IAM Role -- trusted by IAM Roles Anywhere
# ---------------------------------------------------------------------------
MASTER_ROLE_NAME="${PREFIX}-master-role"
echo ""
echo "==> Creating UC Master IAM Role: ${MASTER_ROLE_NAME}"

MASTER_TRUST_POLICY=$(cat <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "rolesanywhere.amazonaws.com"
      },
      "Action": [
        "sts:AssumeRole",
        "sts:SetSourceIdentity",
        "sts:TagSession"
      ]
    }
  ]
}
POLICY
)

MASTER_ROLE_ARN="$(
  aws iam create-role \
    --role-name "${MASTER_ROLE_NAME}" \
    --assume-role-policy-document "${MASTER_TRUST_POLICY}" \
    --query 'Role.Arn' --output text 2>/dev/null \
  || aws iam get-role --role-name "${MASTER_ROLE_NAME}" --query 'Role.Arn' --output text
)"
echo "    Master Role ARN: ${MASTER_ROLE_ARN}"

# The master role needs permission to assume the data access role.
MASTER_POLICY_NAME="${PREFIX}-master-assume-policy"
MASTER_INLINE_POLICY=$(cat <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "sts:AssumeRole",
        "sts:TagSession"
      ],
      "Resource": "arn:aws:iam::${ACCOUNT_ID}:role/${PREFIX}-data-access-role"
    }
  ]
}
POLICY
)

aws iam put-role-policy \
  --role-name "${MASTER_ROLE_NAME}" \
  --policy-name "${MASTER_POLICY_NAME}" \
  --policy-document "${MASTER_INLINE_POLICY}"

# ---------------------------------------------------------------------------
# Data Access IAM Role -- assumed by the UC server via STS
# ---------------------------------------------------------------------------
DATA_ROLE_NAME="${PREFIX}-data-access-role"
echo ""
echo "==> Creating Data Access IAM Role: ${DATA_ROLE_NAME}"

# Initial trust policy trusts only the master role.
# demo.sh will update this to add the sts:ExternalId condition after
# the credential is created (the external_id is generated server-side).
DATA_TRUST_POLICY=$(cat <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "${MASTER_ROLE_ARN}"
      },
      "Action": "sts:AssumeRole",
      "Condition": {
        "StringEquals": {
          "sts:ExternalId": "PLACEHOLDER"
        }
      }
    }
  ]
}
POLICY
)

DATA_ROLE_ARN="$(
  aws iam create-role \
    --role-name "${DATA_ROLE_NAME}" \
    --assume-role-policy-document "${DATA_TRUST_POLICY}" \
    --query 'Role.Arn' --output text 2>/dev/null \
  || aws iam get-role --role-name "${DATA_ROLE_NAME}" --query 'Role.Arn' --output text
)"
echo "    Data Access Role ARN: ${DATA_ROLE_ARN}"

# Grant the data role read/write access to the S3 bucket.
DATA_POLICY_NAME="${PREFIX}-data-s3-policy"
DATA_INLINE_POLICY=$(cat <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "s3:GetObject",
        "s3:PutObject",
        "s3:DeleteObject",
        "s3:ListBucket",
        "s3:GetBucketLocation",
        "s3:AbortMultipartUpload",
        "s3:ListMultipartUploadParts"
      ],
      "Resource": [
        "arn:aws:s3:::${BUCKET_NAME}",
        "arn:aws:s3:::${BUCKET_NAME}/*"
      ]
    }
  ]
}
POLICY
)

aws iam put-role-policy \
  --role-name "${DATA_ROLE_NAME}" \
  --policy-name "${DATA_POLICY_NAME}" \
  --policy-document "${DATA_INLINE_POLICY}"

# ---------------------------------------------------------------------------
# IAM Roles Anywhere -- Trust Anchor + Profile
# ---------------------------------------------------------------------------
echo ""
echo "==> Creating IAM Roles Anywhere Trust Anchor"

CA_CERT_BODY="$(cat "${CERT_DIR}/ca.crt")"

TRUST_ANCHOR_ARN="$(
  aws rolesanywhere create-trust-anchor \
    --name "${PREFIX}-trust-anchor" \
    --source "sourceType=CERTIFICATE_BUNDLE,sourceData={x509CertificateData=\"${CA_CERT_BODY}\"}" \
    --enabled \
    --region "${AWS_REGION}" \
    --query 'trustAnchor.trustAnchorArn' --output text
)"
echo "    Trust Anchor ARN: ${TRUST_ANCHOR_ARN}"

echo ""
echo "==> Creating IAM Roles Anywhere Profile"

PROFILE_ARN="$(
  aws rolesanywhere create-profile \
    --name "${PREFIX}-profile" \
    --role-arns "${MASTER_ROLE_ARN}" \
    --enabled \
    --region "${AWS_REGION}" \
    --query 'profile.profileArn' --output text
)"
echo "    Profile ARN: ${PROFILE_ARN}"

# ---------------------------------------------------------------------------
# Write .env
# ---------------------------------------------------------------------------
cat > "${ENV_FILE}" <<EOF
# Generated by setup-aws.sh -- do not commit
AWS_REGION=${AWS_REGION}
ACCOUNT_ID=${ACCOUNT_ID}
RESOURCE_PREFIX=${PREFIX}
BUCKET_NAME=${BUCKET_NAME}
MASTER_ROLE_NAME=${MASTER_ROLE_NAME}
MASTER_ROLE_ARN=${MASTER_ROLE_ARN}
DATA_ROLE_NAME=${DATA_ROLE_NAME}
DATA_ROLE_ARN=${DATA_ROLE_ARN}
TRUST_ANCHOR_ARN=${TRUST_ANCHOR_ARN}
PROFILE_ARN=${PROFILE_ARN}
EOF

echo ""
echo "Resource identifiers written to ${ENV_FILE}"
echo ""
echo "Next steps:"
echo "  1. Run ./configure-uc.sh to generate server.properties"
echo "  2. Start the UC server"
echo "  3. Run ./demo.sh to exercise credential vending"
