openapi: 3.0.0
servers:
  - url: http://localhost:8080/api/1.0/unity-control
    description: Localhost reference server
tags:
  - name: Users
    description: |
      A user is the identity recognized by Unity Catalog.

paths:
  /scim2/Users:
    post:
      tags:
        - Users
      operationId: createUser
      summary: Create a user
      description: |
        Creates a new user.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserResource'
      responses:
        '200':
          description: The new user was successfully created.
          content:
            application/scim+json:
              schema:
                $ref: '#/components/schemas/UserResource'
    get:
      tags:
        - Users
      parameters:
        - name: filter
          in: query
          description: Query by which the results have to be filtered.
          schema:
            type: string
          required: false
        - name: startIndex
          in: query
          description: Specifies the index of the first result. First item is number 1.
          schema:
            type: integer
            format: int32
          required: false
        - name: count
          in: query
          description: Desired number of results per page. If no count is provided, it defaults to 50.
          schema:
            type: integer
            format: int32
          required: false
      operationId: listUsers
      summary: List users
      description: |
        Gets details for all the users.
      responses:
        '200':
          description: The user list was successfully retrieved.
          content:
            application/scim+json:
              schema:
                $ref: '#/components/schemas/UserResourceList'
  /scim2/Users/{id}:
    parameters:
      - name: id
        in: path
        description: The id of the user.
        required: true
        schema:
          type: string
    get:
      tags:
        - Users
      operationId: getUser
      summary: Get a user
      description: |
        Gets the specified user.
      responses:
        '200':
          description: The user was successfully retrieved.
          content:
            application/scim+json:
              schema:
                $ref: '#/components/schemas/UserResource'
    put:
      tags:
        - Users
      operationId: updateUser
      summary: Update a user
      description: |
        Updates the user that matches the supplied id.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserResource'
      responses:
        '200':
          description: The user was successfully updated.
          content:
            application/scim+json:
              schema:
                $ref: '#/components/schemas/UserResource'
    delete:
      tags:
        - Users
      operationId: deleteUser
      summary: Delete a user
      description: |
        Deletes the user that matches the supplied id.
      responses:
        '200':
          description: The user was successfully deleted.
          content:
            application/scim+json:
              schema: {}
  /scim2/Me:
    get:
      tags:
        - Users
      operationId: getSelf
      summary: Get the current user
      description: |
        Gets the user from the jwt token provided.
      responses:
        '200':
          description: The user was successfully retrieved.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResource'
  /auth/tokens:
    post:
      tags:
        - OAuth2
      parameters:
        - in: query
          name: ext
          description: Specifies whether the server will store a token in the user agent's cookie.
          schema:
            $ref: '#/components/schemas/TokenEndpointExtensionType'
          required: false
      operationId: getToken
      summary: Get a token using an OAuth2 flow
      description: |
        Exchanges credentials for a token using the OAuth2 token exchange.
      # NOTE:
      # When specifying `application/x-www-form-urlencoded` as the content type in the OpenAPI schema,
      # the OpenAPI Generator does not generate request models from the schema.
      # Additionally, accessing parameters directly from the body without a model causes issues with
      # Armeria, particularly when the `ext` query parameter is present.
      #
      # To address this, the same request model is defined here and in `components/schemas/OAuthTokenExchangeForm`.
      # These two definitions MUST be identical.
      # The generated model from `components/schemas/OAuthTokenExchangeForm` will be used
      # in both the `controlApi` and `cli` projects.
      #
      # SEE:
      # - https://armeria.dev/docs/server-annotated-service/#getting-a-query-parameter
      # - https://armeria.dev/docs/server-annotated-service/#injecting-a-parameter-as-an-enum-type
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              description: |
                OAuth2 token exchange request form.
                See https://datatracker.ietf.org/doc/html/rfc8693
              type: object
              required:
                - grant_type
                - subject_token
                - subject_token_type
              properties:
                grant_type:
                  $ref: "#/components/schemas/GrantType"
                scope:
                  description: The authorization scope for the token exchange request.
                  type: string
                requested_token_type:
                  $ref: '#/components/schemas/TokenType'
                subject_token:
                  description: The security token that represents the identity of the party on behalf of whom the request is being made.
                  type: string
                subject_token_type:
                  $ref: '#/components/schemas/TokenType'
                actor_token:
                  description: The security token that represents the identity of the acting party.
                  type: string
                actor_token_type:
                  $ref: '#/components/schemas/TokenType'
      responses:
        '200':
          description: The token exchange was successfully granted.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OAuthTokenExchangeInfo'
  /auth/logout:
    post:
      tags:
        - OAuth2
      operationId: logout
      summary: Revoke access token cookie
      description: |
        Revokes the access token cookie.
      # NOTE:
      # OAS 3.0 allows empty request bodies. In other words:
      #```
      #  requestBody:
      #    content:
      #      application/json: {}
      #```
      # should be permissible. However, due to the limitations of the OpenAPI Generator, which only
      # accepts OAS 2-style notation, this is a workaround.
      # SEE:
      # - https://github.com/OpenAPITools/openapi-generator/blob/v5.1.0/docs/generators/java.md#parameter-feature
      requestBody:
        content:
          application/json:
            schema:
              type: object
              nullable: true
      responses:
        '200':
          description: The access token will be revoked.

components:
  schemas:
    User:
      properties:
        id:
          description: The unique identifier of the user.
          type: string
        name:
          description: The name of the user.
          type: string
        email:
          description: The email address of the user.
          type: string
        external_id:
          description: The external identifier of the user.
          type: string
        state:
          description: The state of the account.
          type: string
          enum:
            - ENABLED
            - DISABLED
        picture_url:
          description: The URL of the user's profile picture.
          type: string
        created_at:
          description: The time the user was created.
          type: integer
          format: int64
        updated_at:
          description: The time the user was last updated.
          type: integer
          format: int64
      type: object
      required:
        - id
        - name
        - email
    UserResourceList:
      description: List of SCIM User resources.
      type: object
      properties:
        totalResults:
          description: The total number of results.
          type: integer
          format: int32
        itemsPerPage:
            description: The number of items per page.
            type: integer
            format: int32
        startIndex:
            description: The index of the first result.
            type: integer
            format: int32
        Resources:
            description: The list of User resources.
            type: array
            items:
                $ref: '#/components/schemas/UserResource'
        id:
            description: User list id metadata.
            type: string
        externalId:
            description: User list external id metadata.
            type: string
        meta:
          description: The metadata of the user.
          type: object
          properties:
            resourceType:
              type: string
            created:
              type: string
            lastModified:
              type: string
    UserResource:
      description: SCIM provides a resource type for "User" resources.
      type: object
      properties:
        id:
          description: The id of the user.
          type: string
        displayName:
          description: The name of the user.
          type: string
        externalId:
          description: The SCIM external id.
          type: string
        emails:
          description: E-mail addresses for the user.
          type: array
          items:
            $ref: '#/components/schemas/Email'
        active:
            description: The active status of the user.
            type: boolean
        meta:
          description: The metadata of the user.
          type: object
          properties:
            created:
              type: string
            lastModified:
              type: string
        photos:
          description: The photos of the user.
          type: array
          items:
            type: object
            properties:
              value:
                description: The url of the user's photo.
                type: string
    Email:
      description: SCIM email for a user.
      type: object
      properties:
        value:
          description: The email of the user.
          type: string
        primary:
          description: If the email is primary.
          type: boolean
    GrantType:
      description: |
        Grant type identifier, from RFC 8693 Section 2.
        See https://datatracker.ietf.org/doc/html/rfc8693#section-2
      type: string
      enum:
        - urn:ietf:params:oauth:grant-type:token-exchange
      # NOTE:
      # OpenAPI 3.0/2.0 do not have a way to define custom names for enum values,
      # but some tools (e.g., openapi-generator and openapi-typescript) provide
      # x-prefixed extensions for this purpose.
      x-enum-varnames:
        - TOKEN_EXCHANGE
    TokenType:
      description: |
        Token type identifier, from RFC 8693 Section 3.
        See https://datatracker.ietf.org/doc/html/rfc8693#section-3
      type: string
      enum:
        - urn:ietf:params:oauth:token-type:access_token
        - urn:ietf:params:oauth:token-type:refresh_token
        - urn:ietf:params:oauth:token-type:id_token
        - urn:ietf:params:oauth:token-type:saml1
        - urn:ietf:params:oauth:token-type:saml2
        - urn:ietf:params:oauth:token-type:jwt
      # NOTE:
      # OpenAPI 3.0/2.0 do not have a way to define custom names for enum values,
      # but some tools (e.g., openapi-generator and openapi-typescript) provide
      # x-prefixed extensions for this purpose.
      x-enum-varnames:
        - ACCESS_TOKEN
        - REFRESH_TOKEN
        - ID_TOKEN
        - SAML1
        - SAML2
        - JWT
    AccessTokenType:
      description: |
        Access token type identifier, from RFC 8693 Section 2.
        See https://datatracker.ietf.org/doc/html/rfc8693#section-2
      type: string
      enum:
        - Bearer
    ResponseType:
      description: |
        Authorization endpoint response type, from RFC 6749 Section 3.
        See https://datatracker.ietf.org/doc/html/rfc6749#section-3
      type: string
      enum:
        - code
        - token
    AuthorizationGrantType:
      description: |
        Authorization grant type, from RFC 6749 Section 4.
        See https://datatracker.ietf.org/doc/html/rfc6749#section-4
      type: string
      enum:
        - authorization_code
    TokenEndpointExtensionType:
      description: |
        The /auth/tokens endpoint supports an extension type.
        If ext=cookie is specified in the request query, the server will store a token in the user agent's cookie.
      type: string
      enum:
        - cookie
    OAuthTokenExchangeForm:
      description: |
        OAuth2 token exchange request form.
        See https://datatracker.ietf.org/doc/html/rfc8693
      type: object
      required:
        - grant_type
        - subject_token
        - subject_token_type
      properties:
        grant_type:
          $ref: "#/components/schemas/GrantType"
        scope:
          description: The authorization scope for the token exchange request.
          type: string
        requested_token_type:
          $ref: '#/components/schemas/TokenType'
        subject_token:
          description: The security token that represents the identity of the party on behalf of whom the request is being made.
          type: string
        subject_token_type:
          $ref: '#/components/schemas/TokenType'
        actor_token:
          description: The security token that represents the identity of the acting party.
          type: string
        actor_token_type:
          $ref: '#/components/schemas/TokenType'
    OAuthTokenExchangeInfo:
      description: |
        OAuth2 token exchange response.
        See https://datatracker.ietf.org/doc/html/rfc8693
      type: object
      required:
        - access_token
        - issued_token_type
        - token_type
      properties:
        access_token:
          description: The access token for the token exchange request.
          type: string
        issued_token_type:
          $ref: '#/components/schemas/TokenType'
        token_type:
          $ref: '#/components/schemas/AccessTokenType'
        expires_in:
          description: The lifetime of the access token in seconds for the token exchange.
          type: integer
          format: int64
        scope:
          description: The authorization scope for the token exchange.
          type: string
        refresh_token:
          description: The refresh token for the token exchange.
          type: string
    OAuthAuthorizationForm:
      description: |
        OAuth2 authorization request form.
        See https://datatracker.ietf.org/doc/html/rfc6749
      type: object
      required:
        - response_type
        - client_id
      properties:
        response_type:
          $ref: '#/components/schemas/ResponseType'
        client_id:
          description: The client identifier that represents the registration information provided by the client
          type: string
        redirect_uri:
          description: The URI that authorization server directs the resource owner's user-agent back to the client.
          type: string
        scope:
          description: The scope of the access request.
          type: string
        state:
          description: An opaque value used by the client to maintain state between the request and callback.
          type: string
    OAuthAuthorizationInfo:
      description: |
        OAuth2 authorization request.
        See https://datatracker.ietf.org/doc/html/rfc6749
      type: object
      required:
        - code
      properties:
        code:
          description: The authorization code generated by the authorization server.
          type: string
        state:
          description: An opaque value used by the client to maintain state between the request and callback.
          type: string
    OAuthAccessTokenForm:
      description: |
        OAuth2 access token request.
        See https://datatracker.ietf.org/doc/html/rfc6749
      type: object
      required:
        - grant_type
        - code
      properties:
        grant_type:
          $ref: "#/components/schemas/AuthorizationGrantType"
        code:
          description: The authorization code received from the authorization server.
          type: string
        redirect_uri:
          description: The URI that authorization server directs the resource owner's user-agent back to the client.
          type: string
        client_id:
          description: The client identifier that represents the registration information provided by the client
          type: string

info:
  title: Unity Control API
  version: '0.1'
