name: Build and Push Docker Images - unitycatalog-ui

on:
  push:
    branches:
      - main
    paths:
      - ui/**
  workflow_dispatch: {}

env:
  IMAGE: unitycatalog/unitycatalog-ui

jobs:
  build-and-push:
    if: false  # Disabled to prevent supply chain attacks; remove this line to restore
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

        # Required for multi-arch builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

        # Will generate tags for the image
        # For ref/tags/*: latest, <tag> 
        # For refs/heads/main: main, main-<short-sha>
      - name: Generate Metadata and Tags
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=ref,event=branch
            type=sha,enable=${{ github.ref == 'refs/heads/main' }},prefix={{branch}}-

      - name: Login to Docker Hub
        if: ${{ contains(fromJSON('["push", "workflow_dispatch"]'), github.event_name) && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main') }}
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        if: ${{ contains(fromJSON('["push", "workflow_dispatch"]'), github.event_name) && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main') }}
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          context: ./ui
          # Push only tagged releases to registry. Eg. the git ref
          # E.g. the commit with short SHA "5d668c1" to main branch would
          # result in the tagged images:
          # "unitycatalog/unitycatalog-ui:main-5d668c1" and
          # "unitycatalog/unitycatalog-ui:main".
          # See here for more info: https://tinyurl.com/yh8252m2
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

          # Use github actions cache: https://docs.docker.com/build/cache/backends/gha/
          cache-from: type=gha
          cache-to: type=gha,mode=max
