name: Python Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Generate Python client library
      run: build/sbt generate

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install requests
        pip install pytest
    - name: Install unitycatalog Python package
      run: |
        source .venv/bin/activate
        pip install target/clients/python/
    - name: Run unit tests
      run: |
        source .venv/bin/activate
        pytest tests/python
