name: Run Integration Tests

on:
  push:
    branches:
      - main  # Change this to be manually triggered
  pull_request:
    branches:
      - main

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run integration tests script
        env:
          VERSION_TO_USE_FOR_INTEGRATION_TESTS: 0.2.1
          STAGING_REPOSITORY_VERSION: 1020
        run: |
          chmod +x ./scripts/run_integration_tests.sh
          ./scripts/run_integration_tests.sh $VERSION_TO_USE_FOR_INTEGRATION_TESTS $STAGING_REPOSITORY_VERSION
