name: OpenAPI Generated Docs Validation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  generated-docs-validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate OpenAPI API and Model docs
        run: build/sbt generate

      - name: Check Generated Docs Differences
        run: |
          git status --porcelain api
          DOCS_DIFF=$(git status --porcelain api | awk '{print $2}')

          if [[ -n $DOCS_DIFF ]]; then
            echo "This PR contains changes that should also update the generated docs using build/sbt generate"
            echo "If you have changed the UC REST APIs such that changes to generated docs are expected, then please make sure all generated docs have been properly updated in this PR."
            echo "Otherwise, without changes to UC REST APIs, manual changes to the generated docs are not acceptable."
            echo "Modified or untracked doc files:"
            echo "$DOCS_DIFF"
            exit 1
          else
            echo "No changes to generated docs detected."
          fi
        shell: bash