name: Tarball Generation Tests

on:
  push:
    branches: ["main"]
    paths:
      - build/**
      - project/**
      - examples/**
      - server/**
      - api/**
      - clients/**
      - bin/**
      - etc/**
      - version.sbt
      - build.sbt
      - tests/test_tarball_generation.py
      - .github/workflows/tarball-gen-tests.yml
  pull_request:
    branches: ["main"]
    paths:
      - build/**
      - project/**
      - examples/**
      - server/**
      - api/**
      - clients/**
      - bin/**
      - etc/**
      - version.sbt
      - build.sbt
      - tests/test_tarball_generation.py
      - .github/workflows/tarball-gen-tests.yml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up JDK 17
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build tarball
        run: build/sbt createTarball

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install requests

      - name: Test tarball
        run: python tests/test_tarball_generation.py
